# Settings file for use with Micro-manager's MMConfig_Demo config. It emulates
# acquiring data from the label-free and light-sheet arms of the microscope

time_settings:
  num_timepoints: 3
  time_interval_s: 5

position_settings:
  xyz_positions:
    - [0, 0, 0]
    - [0, 0, 1]
    - [0, 0, 2]
  position_labels:
    - 'One-Pos001'
    - 'Two-Pos002'
    - 'Three-Pos003'
  
lf_channel_settings:
  default_exposure_times_ms: [10, 10]
  channel_group: 'Channel-Multiband'
  channels: ['DAPI', 'FITC']
  use_sequencing: True

lf_slice_settings:
  z_stage_name: 'Z'
  z_start: -5
  z_end: 5
  z_step: 0.205
  use_sequencing: True

lf_microscope_settings:
  config_group_settings:
    - ['LightPath', 'Camera-left']
  device_property_settings:
    - ['Camera', 'OnCameraCCDXSize', '1224']
    - ['Camera', 'OnCameraCCDYSize', '1024']
    - ['Camera', 'BitDepth', '12']
  z_sequencing_settings:
    - ['Z', 'UseSequences', 'Yes']
  channel_sequencing_settings:
    - ['LED', 'Sequence', 'On']
  use_autofocus: False

ls_channel_settings:
  default_exposure_times_ms: [20, 30]
  default_laser_powers: [2, 5]
  channel_group: 'Channel'
  channels: ['Rhodamine', 'Cy5']
  use_sequencing: False
  use_autoexposure: [False, False]

ls_slice_settings:
  z_stage_name: 'Z'
  z_start: -6  # in micrometers
  z_end: 6
  z_step: 0.313  # equivalent to 10 mV
  use_sequencing: True

ls_microscope_settings:
  roi: [0, 896, 2048, 256]
  config_group_settings:
    - ['LightPath', 'Camera-right']
  device_property_settings:
    - ['Camera', 'OnCameraCCDXSize', '2048']
    - ['Camera', 'OnCameraCCDYSize', '2048']
    - ['Camera', 'BitDepth', '12']
  z_sequencing_settings:
    - ['Z', 'UseSequences', 'Yes']

# Zarr output settings for the label-free acquisition (demo)
lf_zarr_settings:
  data_type: 'UINT16'
  multiscale: false
  max_threads: 2  # limit threads for demo
  chunk_sizes:
    x: 64
    y: 64
    z: 1
    c: 1
    p: 1
    t: 1
  shard_size_chunks: 1
  compression_codec: 'gzip'  # simple compression for demo
  compression_level: 3
  overwrite_existing: true  # allow overwriting for demos

# Zarr output settings for the light-sheet acquisition (demo)
ls_zarr_settings:
  data_type: 'UINT16'
  multiscale: false
  max_threads: 2  # limit threads for demo
  chunk_sizes:
    x: 64
    y: 64
    z: 1
    c: 1
    p: 1
    t: 1
  shard_size_chunks: 1
  compression_codec: 'gzip'  # simple compression for demo
  compression_level: 3
  overwrite_existing: true  # allow overwriting for demos
