# Typical workflows use `estimate-registration` to generate these config files.
source_channel_names: [Phase3D, Orientation, Retardance, Birefringence]
target_channel_name: GFP # Single target channel. All others channels in target store are copied.
affine_transform_zyx: # in pixel units, i.e. not scaled
- [1.0, 0.0, 0.0, 0.0]
- [0.0, 1.0, 0.0, 0.0]
- [0.0, 0.0, 1.0, 0.0]
- [0.0, 0.0, 0.0, 1.0]
keep_overhang: false   # Optional, if true datasets will have non-overlapping regions
time_indices: all  # Optional, by default all time indices are processed
