name: pull-request-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Ruff lint
      uses: astral-sh/ruff-action@v3

    - name: Ruff format
      uses: astral-sh/ruff-action@v3
      with:
        args: "format --check"

  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for hatch-vcs

    - name: Checkout pymmcore-plus
      uses: actions/checkout@v4
      with:
        repository: ieivanov/pymmcore-plus
        path: pymmcore-plus

    - name: Checkout ome-writers
      uses: actions/checkout@v4
      with:
        repository: ieivanov/ome-writers
        path: ome-writers

    - name: Move editable sources to expected paths
      shell: bash
      run: |
        mv pymmcore-plus ../pymmcore-plus
        mv ome-writers ../ome-writers

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: uv sync

    - name: Run tests
      run: make test
