name: pull-request-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, 170-migrate-to-pymmcore-plus]

jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the mantis package
      run: pip install -e ".[dev]"

    - name: Check code style with Black
      run: black --check -t py310 .

    - name: Check code with Flake8
      run: flake8 .

    - name: Check code with isort
      run: isort --check .

  pytest:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the mantis package
      run: pip install -e ".[dev]"

    - name: Run tests
      run: pytest -vvV
